
import { GoogleGenAI } from "@google/genai";
import { PosterConfig } from "../types";

export class GeminiService {
  private static getAI() {
    return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  static async generatePoster(
    base64Image: string, 
    config: PosterConfig,
    isHighQuality: boolean = false
  ): Promise<string> {
    const ai = this.getAI();
    const modelName = isHighQuality ? 'gemini-3-pro-image-preview' : 'gemini-2.5-flash-image';
    
    // Constructing the prompt based on user requirements
    const prompt = `
      You are a professional commercial graphic designer. 
      TASK: Transform this uploaded product image into a high-quality promotional poster.
      
      CORE RULES:
      - The uploaded product image MUST be the main focus.
      - Do NOT distort or change the original product shape.
      - Enhance lighting, color, and sharpness naturally to studio photography standards.
      - Design a professional commercial advertisement background matching the category of "${config.productName}".
      
      TEXT & LAYOUT:
      - Add typography with a high-end feel.
      - PRODUCT TITLE: "${config.productName}" (Main visual title, bold, modern font).
      - PRICE BADGE: ${config.price ? `Create a professional price badge showing "${config.price}". Use a modern rounded shape or sticker style that contrasts well but is harmonious.` : 'No price badge needed.'}
      - PRODUCT DETAILS: "${config.details}" (Small, elegant font, minimal, do not overcrowd).
      - Ensure all text is legible and does not cover the product itself.
      
      VISUAL STYLE:
      - Realistic, high detail, studio lighting.
      - Clean, modern, premium aesthetic.
      - Final aspect ratio: ${config.ratio}.
    `;

    try {
      const response = await ai.models.generateContent({
        model: modelName,
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Image.split(',')[1],
                mimeType: 'image/png',
              },
            },
            { text: prompt },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: config.ratio as any,
            // imageSize only for gemini-3-pro-image-preview
            ...(modelName === 'gemini-3-pro-image-preview' ? { imageSize: config.quality } : {})
          }
        }
      });

      // Find image part in response
      let imageUrl = '';
      if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
            break;
          }
        }
      }

      if (!imageUrl) {
        throw new Error("No image was generated by the model.");
      }

      return imageUrl;
    } catch (error) {
      console.error("Gemini Poster Generation Error:", error);
      throw error;
    }
  }
}
